export { default as Dashboard } from './dashboard';
export { default as Account } from './account';
export { default as Customers } from './customer';
export { default as Wallet } from './wallet';
export { default as Product } from './product';
export { default as Sale } from './sale';
export { default as Reports } from './report';
export { default as Setting } from './setting';
export { default as NotFound } from './notfound';